# Generated by Django 4.2.27 on 2026-02-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, help_text='General information about the medicine', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('branded', 'Branded'), ('generic', 'Generic')], default='branded', max_length=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, help_text='Common side effects', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='uses',
            field=models.TextField(blank=True, help_text='Common uses of this medicine', null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('mrp', 'Maximum Retail Price'), ('average', 'Average Market Price'), ('online', 'Online Price')], default='average', max_length=10),
        ),
    ]
